version: '3.8'

networks:
  web:
    external: true

services:
  api:
    build:
      context: .
      target: dev
    container_name: ssc-api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 3000:3000
    networks:
      - web

  postgres:
    image: postgres:14-alpine
    container_name: ssc-postgres
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ssc-booking
    networks:
      - web

  redis:
    image: redis:7-alpine
    container_name: ssc-redis
    ports:
      - 6379:6379
    networks:
      - web

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: ssc-redis
      REDIS_PORT: 6379:6379
    ports:
      - 8081:8081
    networks:
      - web