export default {
  data: [
    {
      name: 'การหักเหของแสง + การเกิดฤดูกาลและนํ้าขึ้นนํ้าลง',
      code: '1101A',
      price: 2000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 1,
    },
    {
      name: 'จรวจขวดน้ำ',
      code: '1102A',
      price: 2000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 1,
    },
    {
      name: 'การวัดและความผิดพลาด',
      code: '1201A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวดิ่ง)',
      code: '1202A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวราบ)',
      code: '1203A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 1,
    },
    {
      name: 'การวัดและความผิดพลาด',
      code: '1301A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวดิ่ง)',
      code: '1302A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวราบ)',
      code: '1303A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่แบบเพนดูลัมอย่างง่าย',
      code: '1304A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่แบบวิถีโค้ง',
      code: '1305A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'ดาราศาสตร์การดูดาวเบื้องต้น',
      code: '1306A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การทดลองทางไฟฟ้า',
      code: '1307A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การทดสอบสารอาหารเบื้องต้น',
      code: '2101A',
      price: 2000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 2,
    },
    {
      name: 'การแยกสารด้วยเทคนิคโครมาโทกราฟีแบบกระดาษ',
      code: '2102A',
      price: 2000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 2,
    },
    {
      name: 'อุปกรณ์พื้นฐานและการกลั่นลำดับส่วน',
      code: '2201A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'การเตรียมสารละลาย',
      code: '2202A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'กรดเบสและอินดิเคเตอร์',
      code: '2203A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'อุปกรณ์พื้นฐานและการแยกสารในชีวิตประจำวัน',
      code: '2204A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'การทดสอบสารอาหารในชีวิตประจำวัน',
      code: '2205A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'โครมาโทรกราฟีระดับมัธยมต้น',
      code: '2206A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'ทดสอบการเปลี่ยนแปลงของสาร',
      code: '2207A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'อุปกรณ์และเครื่องมือพื้นฐานและการแยกสารผสม',
      code: '2208A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 2,
    },
    {
      name: 'การตกผลึก',
      code: '2301A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'การสกัด',
      code: '2302A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'โครมาโทรกราฟีระดับมัธยมปลาย',
      code: '2303A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'อุปกรณ์พื้นฐานและการกลั่น',
      code: '2304A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'การหาองค์ประกอบของสารประกอบไอออนิค',
      code: '2305A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'องค์ประกอบทางเคมีและสมบัติการเกิดยิปซัม',
      code: '2306A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'อุปกรณ์และเครื่องมือพื้นฐานและการเตรียมสารละลาย',
      code: '2307A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'การใช้เครื่องมือพื้นฐานและเทคนิคการไทเทรต',
      code: '2308A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'ทดสอบน้ำตาลด้วยเทคนิคโครมาโทกราฟี',
      code: '2309A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'สมดุลเคมี',
      code: '2310A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'การหาค่าคงที่ของแก๊ส',
      code: '2311A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'เคมีไฟฟ้า',
      code: '2312A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'กรด-เบส',
      code: '2313A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 2,
    },
    {
      name: 'หลักการเบื้องต้นในการใช้กล้องจุลทรรศน์เพื่อศึกษาสิ่งมีชีวิต (ชีววิทยา)',
      code: '3201A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 3,
    },
    {
      name: 'ศึกษาระบบทางเดินอาหาร (ชีววิทยา)',
      code: '3202A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 3,
    },
    {
      name: 'ศึกษาระบบการสืบพันธุ์ (ชีววิทยา)',
      code: '3203A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 3,
    },
    {
      name: 'โครงสร้างและการสืบพันธุ์ของพืชดอก (ชีววิทยา)',
      code: '3204A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 3,
    },
    {
      name: 'การสังเคราะห์ด้วยแสง (ชีววิทยา)',
      code: '3205A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 3,
    },
    {
      name: 'ระบบนิเวศ (ชีววิทยา)',
      code: '3206A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 3,
    },
    {
      name: 'กรดนิวคลีอิกและกิจกรรม (ชีววิทยา)',
      code: '3301A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'สีย้อมโครโมโซมจากพืชเพื่อศึกษาไมโทซีสและไมโอซีส (ชีววิทยา)',
      code: '3302A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'เทคนิคการเพาะเลี้ยงเนื้อเยื่อพืชอย่างง่าย (ชีววิทยา)',
      code: '3303A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'ไบโอเทคกับการสกัดดีเอ็นเอพื้นฐาน (เทคโนโลยีชีวภาพ)',
      code: '3401A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'นักสืบไบโอเทคด้านชีวโมเลกุล (เทคโนโลยีชีวภาพ)',
      code: '3402A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'ไบโอเทคด้านชีวโมเลกุล (รวม 310 + 311) (เทคโนโลยีชีวภาพ)',
      code: '3403A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'แบคทีเรียกับการเตรียมโยเกิร์ต (เทคโนโลยีชีวภาพ)',
      code: '3404A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'โครงสร้างและการหายใจของยีสต์ (เทคโนโลยีชีวภาพ)',
      code: '3405A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'ยีสต์เป่าลูกโป่งและขนมปังไบโอเทคจากยีสต์ (เทคโนโลยีชีวภาพ)',
      code: '3406A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'ยีสต์กับการประยุกต์ใช้ทางไบโอเทค (รวม 314 + 315) (เทคโนโลยีชีวภาพ)',
      code: '3407A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'การใช้กล้องจุลทรรศน์ศึกษาจุลินทรีย์ (จุลชีววิทยา)',
      code: '3501A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'เทคนิคการเพาะเลี้ยงจุลินทรีย์บนอาหารเลี้ยงเชื้อ (จุลชีววิทยา)',
      code: '3502A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'การวัดขนาดและนับจำนวนจุลินทรีย์ภายใต้กล้องจุลทรรศน์ (จุลชีววิทยา)',
      code: '3503A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'การตรวจสอบคุณภาพทางจุลชีววิทยาของน้ำบริโภค (จุลชีววิทยา)',
      code: '3504A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'เทคนิคการหาปริมาณจุลินทรีย์ทั้งหมดในอาหาร (จุลชีววิทยา)',
      code: '3505A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 3,
    },
    {
      name: 'การเตรียมหัวเชื้อข้าวฟ่างและการถ่ายเนื้อเยื่อเห็ด (ชีววิทยา)',
      code: '3601A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 3,
    },
    {
      name: 'การเตรียมสีย้อมจากพืชเพื่อใช้ในการศึกษาโครโมโซม/เซลล์ (ชีววิทยา)',
      code: '3602A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 3,
    },
    {
      name: 'ไวน์ไบโอเทค (เทคโนโลยีชีวภาพ)',
      code: '3603A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 3,
    },
    {
      name: 'ไซเดอร์ไบโอเทค (เทคโนโลยีชีวภาพ)',
      code: '3604A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 3,
    },
    {
      name: 'การตรวจสอบคุณภาพทางจุลชีววิทยาของน้ำบริโภค (จุลชีววิทยา)',
      code: '3605A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 3,
    },
    {
      name: 'เทคนิคการหาปริมาณจุลินทรีย์ทั้งหมดในอาหาร (จุลชีววิทยา)',
      code: '3606A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 3,
    },
    {
      name: 'ค่ายคณิตศาสตร์ STEM MATH ระดับประถมฯ (สำหรับคอร์ส 9 ชั่วโมงขึ้นไป)',
      code: '4101C',
      price: 6000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 4,
    },
    {
      name: 'ค่ายคณิตศาสตร์ STEM MATH ระดับประถมฯ (สำหรับคอร์ส 12 ชั่วโมงขึ้นไป)',
      code: '4101D',
      price: 8000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 4,
    },
    {
      name: 'เตรียมความพร้อมสอบ O-Net ระดับมัธยมต้น',
      code: '4201A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 4,
    },
    {
      name: 'ค่ายคณิตศาสตร์ STEM Math ระดับมัธยมต้น (สำหรับคอร์ส 9 ชั่วโมงขึ้นไป)',
      code: '4202C',
      price: 6000,
      level: 'มัธยมต้น',
      subjectCategoryId: 4,
    },
    {
      name: 'ค่ายคณิตศาสตร์ STEM Math ระดับมัธยมต้น (สำหรับคอร์ส 12 ชั่วโมงขึ้นไป)',
      code: '4202B',
      price: 4000,
      level: 'มัธยมต้น',
      subjectCategoryId: 4,
    },
    {
      name: 'เตรียมความพร้อมสอบ O-Net ม.6',
      code: '4301A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 4,
    },
    {
      name: 'ค่ายเตรียมพร้อมสอบคณิตศาสตร์ A-Level ม.6',
      code: '4302A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 4,
    },
    {
      name: 'อบรมเชิงปฏิบัติการใช้งานโปรแกรม Geogebra',
      code: '4303A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 4,
    },
    {
      name: 'อบรมเชิงปฏิบัติการใช้งานโปรแกรม Geogebra (สำหรับครูคณิตศาสตร์)',
      code: '4401A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 4,
    },
    {
      name: 'ตรียมความพร้อมสอบ ก.พ. ภาค ก. วิชาคณิตศาสตร์ทั่วไป (สำหรับบุคคลทั่วไป)',
      code: '4402A',
      price: 2000,
      level: 'ทั่วไป',
      subjectCategoryId: 4,
    },
    {
      name: 'พื้นฐานการใช้งาน Google Application',
      code: '5201B',
      price: 4000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'พื้นฐานการใช้งาน MS Teams',
      code: '5202B',
      price: 4000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'โปรแกรมสำเร็จรูปสำหรับการนำเสนองาน',
      code: '5203A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'การทำโปรไฟล์นักเรียนโดยใช้ Canva',
      code: '5204A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'การวิเคราะห์ข้อมูลเชิงสถิติอย่างง่ายโดยใช้โปรแกรม R',
      code: '5205B',
      price: 4000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'การเขียนโปรแกรมไพธอนเบื้องต้น',
      code: '5206B',
      price: 4000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'การทำ Info Graphic โดยใช้ Canva',
      code: '5207A',
      price: 2000,
      level: 'มัธยมต้น',
      subjectCategoryId: 5,
    },
    {
      name: 'การเขียนแอปพลิเคชันเกมบนมือถืออย่างง่าย',
      code: '5301B',
      price: 4000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 5,
    },
    {
      name: 'การวิเคราะห์ข้อมูลเชิงสถิติโดยใช้โปรแกรม Spread Sheet',
      code: '5302B',
      price: 4000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 5,
    },
    {
      name: 'การทำโปรไฟล์นักเรียนโดยใช้ Canva (Advanced)',
      code: '5303A',
      price: 2000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 5,
    },
    {
      name: 'การวิเคราะห์ข้อมูลเชิงสถิติโดยใช้โปรแกรม R',
      code: '5304B',
      price: 4000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 5,
    },
    {
      name: 'การเขียนโปรแกรมไพธอน',
      code: '5305B',
      price: 4000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 5,
    },
    {
      name: 'การวิเคราะห์ข้อมูลเชิงสถิติโดยใช้โปรแกรมสำเร็จรูป',
      code: '5306B',
      price: 4000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 5,
    },
    {
      name: '(รออัพเดท)',
      code: '5401A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 5,
    },
    {
      name: 'พอลิเมอร์เบื้องต้น',
      code: '6101A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 6,
    },
    {
      name: 'การแปรรูปยางเบื้องต้น',
      code: '6102A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 6,
    },
    {
      name: 'การปลูกผักไฮโดรโบนิกส์ทำเอง ขั้นต้น',
      code: '6201A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 6,
    },
    {
      name: 'การปลูกผักไฮโดรโบนิกส์ทำเอง ขั้นกลาง',
      code: '6202A',
      price: 2000,
      level: 'มัธยมต้น/ปลาย',
      subjectCategoryId: 6,
    },
    {
      name: 'การแปรรูปผลิตภัณฑ์การเกษตร (ไก่ส้ม)',
      code: '6301A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 6,
    },
    {
      name: 'การแปรรูปผลิตภัณฑ์การเกษตร (การหมักข้าวหมาก)',
      code: '6302A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 6,
    },
    {
      name: 'การแปรรูปผลิตภัณฑ์การเกษตร (เทมเป้)',
      code: '6303A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 6,
    },
    {
      name: 'การแปรรูปผลิตภัณฑ์การเกษตร (แหนมไก่)',
      code: '6304A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 6,
    },
    {
      name: 'การเพาะเลี้ยงจุลินทรีย์เพื่อการประยุกต์ใช้แบคทีเรียทางการเกษตร',
      code: '6305A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 6,
    },
    {
      name: '(รออัพเดท)',
      code: '7101A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 7,
    },
    {
      name: '(รออัพเดท)',
      code: '8101A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 8,
    },
    {
      name: '(รออัพเดท)',
      code: '9101A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 9,
    },
    {
      name: '(รออัพเดท)',
      code: '9201A',
      price: 2000,
      level: 'อบรมทั่วไป',
      subjectCategoryId: 9,
    },
  ],
}
