export default {
  data: [
    {
      name: 'การหักเหของแสง + การเกิดฤดูกาลและนํ้าขึ้นนํ้าลง',
      code: '1101A',
      price: 1000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 1,
    },
    {
      name: 'จรวจขวดน้ำ',
      code: '1102A',
      price: 1000,
      level: 'ประถมศึกษา',
      subjectCategoryId: 1,
    },
    {
      name: 'การวัดและความผิดพลาด',
      code: '1201A',
      price: 1000,
      level: 'มัธยมต้น',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวดิ่ง)',
      code: '1202A',
      price: 1000,
      level: 'มัธยมต้น',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวราบ)',
      code: '1203A',
      price: 1000,
      level: 'มัธยมต้น',
      subjectCategoryId: 1,
    },
    {
      name: 'การวัดและความผิดพลาด',
      code: '1301A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวดิ่ง)',
      code: '1302A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่ 1 มิติ (แนวราบ)',
      code: '1303A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่แบบเพนดูลัมอย่างง่าย',
      code: '1304A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การเคลื่อนที่แบบวิถีโค้ง',
      code: '1305A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'ดาราศาสตร์การดูดาวเบื้องต้น',
      code: '1306A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
    {
      name: 'การทดลองทางไฟฟ้า',
      code: '1307A',
      price: 1000,
      level: 'มัธยมปลาย',
      subjectCategoryId: 1,
    },
  ],
}
